name: CI with SonarQube

on:
  push:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: windows-latest
    services:
      sonarqube:
        image: sonarqube:lts
        ports:
          - 9000:9000
        options: >-
          --health-cmd "curl -s http://localhost:9000/api/system/health | grep -q '\"status\":\"GREEN\"'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build (example using Maven)
        run: |
          ./mvnw clean verify

      - name: Wait for SonarQube to be ready
        run: |
          sleep 30  # или до health-check

      - name: Run Sonar Scanner
        uses: sonarsource/sonarqube-scan-action@master
        with:
          host-url: 'http://localhost:9000'
          token: ${{ secrets.SONAR_TOKEN }}
